### ISSUE TITLE
Calculate risk of contracting COVID-19 based on symptoms

### ISSUE THREAD

**Issue by xindyhu** [mathematica-mpr/covid_risk_score#21]
The app now has two ways of calculating COVID-19 risks:
1) If someone is experiencing flu-like symptoms, exposure_risk = total_covid_probability / (total_covid_probability + prob_flu).
2) If someone does not currently have flu-like symptoms, exposure_risk is a function of the prevalence of COVID in the community and the number of close contacts.

We would like to update 1) based on the latest symptomology data from CDC. Table 2 of [this document](https://www.cdc.gov/mmwr/volumes/69/wr/mm6924e2.htm).
Expand the single check-box on whether one has flu-like symptoms to multiple symptoms, and calculate the likelihood of someone with COVID based on the symptoms they reported.

I am not 100% sure this will give us what we want because everybody in the sample has COVID. Alternatively, [this publication from Nature Medicine](https://www.nature.com/articles/s41591-020-0916-2) may be a better fit. It has OR of symptoms to predict COVID-19.

**Comment by 2sls** [comment]
This calculator inspired me so just some thoughts:

It looks like the transmission probability is _daily_  - is this correct?

It looks like the probability is measured off the fraction of population that is positive for covid - plus some adjustment factors for undercounting and the number of daily contacts. 

Maybe I missed it but is there a parameter that captures the probability of transmission conditional on being exposed to a positive case?

**Comment by xindyhu** [comment]
@2sls Thanks for your comments.
The exposure of catching COVID-19 from community transmission is estimated as a function of the number of close contacts one has in a week and the prevalence of active cases in the community. The time frame is a week.

For the probability of transmission conditional on being exposed, we use the higher-end estimate (close household contact, rather than general contact) from this CDC MMWR.
https://www.cdc.gov/mmwr/volumes/69/wr/pdfs/mm6909e1-H.pdf

**Comment by 2sls** [comment]
Thanks for the link @xindyhu - this is really helpful.

I took a quick look and the key limitation of that study is that it doesn't actually measure the duration of exposure. The only requirement of a close contact is having 10 minutes+, but since only 2 out of the 445 close contacts got positive, and those 2 were both household members of patient zeros, they likely got days or weeks of exposure prior to isolation.  So the reported attack rate of 10.5% is most certainly an upper bound for something like the transmission rate per 10 minute exposure interval.

Nevertheless, there probably isn't anything better to use at the moment.
