### ISSUE TITLE
Error in probability calculation

### ISSUE THREAD

**Issue by LoisRP** [mathematica-mpr/covid_risk_score#42]
With the parameters I selected, I got this statement in the report:
"Among people who are the same age, sex, and health status as you and get sick from COVID-19, the risk of hospitalization is 12% , the risk of requiring an ICU is 21% , and the risk of dying is 0.65% ."

However, I think what you mean is that the risk of requiring an ICU is 0.21*0.12, because obviously one cannot receive ICU treatment without being hospitalized in the first place. Please confirm what you mean here, as it makes me suspicious of the results in general. 

(Thanks for the calculator - I find it very interesting to test.)

**Comment by xindyhu** [comment]
@LoisRP Thank you for bringing this up! We are aware of this and are currently fixing it. The reason is we did not find a mutually adjusted odds ratio for age, sex and different comorbidities the probability of ICU, so we used the most severe comorbidity as a proxy but it may still produce over-estimation. Like you have rightfully pointed out here. We will keep looking for mutually adjusted ORs, or implement ad hoc adjustment to account for the age distribution of comorbidities. A short term solution is to add some language in the output to clarify this point, which we hope to get to next week.
