### ISSUE TITLE
Calculator - Differentiate between Type 1 and Type 2 Diabetes

### ISSUE THREAD

**Issue by JamesIgoe** [mathematica-mpr/covid_risk_score#46]
I shared this calculator in a forum for Type 1 diabetics, and someone raised the question fo whether it mattered if one was Type 1 or Type 2.

Can you clarify?

**Comment by xindyhu** [comment]
@JamesIgoe Great question! To calculate the probability of hospitalization/ICU/death, we relied on the following three studies.

- Hospitalization: https://www.cdc.gov/mmwr/volumes/69/wr/mm6925e1.htm
- ICU: https://www.cdc.gov/mmwr/volumes/69/wr/mm6913e2.htm
- Death: https://www.nature.com/articles/s41586-020-2521-4

They did not distinguish Type 1 and Type 2, which is why we did not specify in our app.
Based on the OPENSAFELY study, there are some differences based on HbA1c levels. So controlled diabetes will have lower risk than uncontrolled. Our app took a weighted average of the two.
![image](https://user-images.githubusercontent.com/8843067/94322765-37602f00-ff48-11ea-9bd8-0db952eda4e7.png)

Based on the CDC website, Type 2 diabetes is a confirmed risk factor while Type 1 might be a risk factor. https://www.cdc.gov/coronavirus/2019-ncov/need-extra-precautions/people-with-medical-conditions.html?CDC_AA_refVal=https%3A%2F%2Fwww.cdc.gov%2Fcoronavirus%2F2019-ncov%2Fneed-extra-precautions%2Fgroups-at-higher-risk.html

Hope it helps. Thank you for sharing the calculator in the forum!

**Comment by JamesIgoe** [comment]
Also, do you know if they differentiate between controlled and uncontrolled hypertension?

**Comment by xindyhu** [comment]
@JamesIgoe We haven't come across that distinction. The evidence for hypertension is a bit mixed based on the CDC summary https://www.cdc.gov/coronavirus/2019-ncov/need-extra-precautions/evidence-table.html
